workflows:
  ios:
    name: Build and Publish iOS
    max_build_duration: 60
    scripts:
      - npm install -g ionic
      - npm install
      - ionic build --prod --platform ios
      - ionic capacitor build ios
    artifacts:
      - build/ios/*.ipa
    publishing:
      provider: app_store_connect
      api_key: $APP_STORE_CONNECT_API_KEY
      app_id: $APP_STORE_APP_ID
      upload_method: auto
  android:
    name: Build and Publish Android
    max_build_duration: 60
    scripts:
      - npm install -g ionic
      - npm install
      - ionic build --prod --platform android
      - ionic capacitor build android
    artifacts:
      - build/android/*.apk
    publishing:
      provider: google_play
      json_key: $PLAY_STORE_JSON_KEY
      app_id: $PLAY_STORE_APP_ID
      upload_method: auto
