workflows:
    ios-workflow-id:
        name: iOS Sample Workflow
        max_build_duration: 120
        instance_type: mac_mini_m2
        
publishing: 
    email:
        recipients:
          - cmoreira1300@gmail.com
          
        notify:
          success: true
          failure: false
