workflows:
  ios:
    name: iOS Workflow
    max_build_duration: 60
    scripts:
      - flutter pub get
      - ionic build --prod
    android:
      - flutter build apk --release
    ios:
      - flutter build ios --release
      - flutter test
      - flutter build ios --release
